apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavindu-pvc
  namespace: pvc-ns
spec:
  volumeName: kavindu-pvc
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
